#!/bin/bash

CUDA_VISIBLE_DEVICES=1 python train.py  torch/cifar100 -d torch/cifar100 --num-classes=100 --val-split test --dataset-download -b=128 --img-size=224 --epochs=50 --color-jitter=0 --amp --lr=1e-2 --sched='cosine' --model-ema --model-ema-decay=0.995 --reprob=0.5 --smoothing=0.1 --min-lr=1e-8 --warmup-epochs=3 --train-interpolation=bilinear --aa=v0 --model=resnet101 --pretrained  --opt=sgd --weight-decay=1e-4 --checkpoint-hist=1  --experiment "cifar100" --name "resnet101 dual.9.1" --log-wandb --dual --dual-weights .9 .1

CUDA_VISIBLE_DEVICES=1 python train.py  tfds/oxford_iiit_pet -d tfds/oxford_iiit_pet --num-classes=37 --val-split test --dataset-download -b=128 --img-size=224 --epochs=50 --color-jitter=0 --amp --lr=1e-2 --sched='cosine' --model-ema --model-ema-decay=0.995 --reprob=0.5 --smoothing=0.1 --min-lr=1e-8 --warmup-epochs=3 --train-interpolation=bilinear --aa=v0 --model=resnet101 --pretrained  --opt=sgd --weight-decay=1e-4 --checkpoint-hist=1  --experiment "oxford_iiit_pet" --name "resnet101 dual.9.1" --log-wandb --dual --dual-weights .9 .1

CUDA_VISIBLE_DEVICES=1 python train.py   tfds/cars196 -d tfds/cars196 --num-classes=196 --val-split test --dataset-download -b=128 --img-size=224 --epochs=50 --color-jitter=0 --amp --lr=1e-2 --sched='cosine' --model-ema --model-ema-decay=0.995 --reprob=0.5 --smoothing=0.1 --min-lr=1e-8 --warmup-epochs=3 --train-interpolation=bilinear --aa=v0 --model=resnet101 --pretrained  --opt=sgd --weight-decay=1e-4 --checkpoint-hist=1  --experiment "cars196" --name "resnet101 dual.9.1" --log-wandb --dual --dual-weights .9 .1

CUDA_VISIBLE_DEVICES=1 python train.py  tfds/food101 -d tfds/food101 --num-classes=101 --val-split validation --dataset-download -b=128 --img-size=224 --epochs=50 --color-jitter=0 --amp --lr=1e-2 --sched='cosine' --model-ema --model-ema-decay=0.995 --reprob=0.5 --smoothing=0.1 --min-lr=1e-8 --warmup-epochs=3 --train-interpolation=bilinear --aa=v0 --model=resnet101 --pretrained  --opt=sgd --weight-decay=1e-4 --checkpoint-hist=1  --experiment "food101" --name "resnet101 dual.9.1" --log-wandb --dual --dual-weights .9 .1

CUDA_VISIBLE_DEVICES=1 python train.py  tfds/stanford_dogs -d tfds/stanford_dogs --num-classes=120 --val-split test --dataset-download -b=128 --img-size=224 --epochs=50 --color-jitter=0 --amp --lr=1e-2 --sched='cosine' --model-ema --model-ema-decay=0.995 --reprob=0.5 --smoothing=0.1 --min-lr=1e-8 --warmup-epochs=3 --train-interpolation=bilinear --aa=v0 --model=resnet101 --pretrained  --opt=sgd --weight-decay=1e-4 --checkpoint-hist=1  --experiment "stanford_dogs" --name "resnet101 dual.9.1" --log-wandb --dual --dual-weights .9 .1

CUDA_VISIBLE_DEVICES=1 python train.py  tfds/oxford_flowers102 -d tfds/oxford_flowers102 --num-classes=102 --num-classes=120 --val-split test --dataset-download -b=128 --img-size=224 --epochs=50 --color-jitter=0 --amp --lr=1e-2 --sched='cosine' --model-ema --model-ema-decay=0.995 --reprob=0.5 --smoothing=0.1 --min-lr=1e-8 --warmup-epochs=3 --train-interpolation=bilinear --aa=v0 --model=resnet101 --pretrained  --opt=sgd --weight-decay=1e-4 --checkpoint-hist=1  --experiment "oxford_flowers102" --name "resnet101 dual.9.1" --log-wandb  --dual --dual-weights .9 .1